#!/bin/bash

number=0

echo -n "How many coins do you want to split? "
read number

amount=$((number/64))

echo "$amount will be sent to your 64 addresses."

sleep 1

echo "Generating the 64 addresses..."

if [ -e list.py ]
then
    echo "You already have them!"
else
    ./genaddresses.py > list.py
fi


echo "Sending $amount to the 64 addresses!"

./sendmany64.py $amount


echo "Done! The result is the txid."

