#!/bin/bash

number=0

echo -n "How many coins do you want to split? "
read number

amount=$((number/64))

echo "Sending $amount to all 64 addresses!"

if [ -e list.py ]
then
    echo "Already have 64 addresses."
else
    ./genaddresses.py > list.py
fi

./sendmany64.py $amount

echo "Done!"

